/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors/index'
import { Route as AuthenticatedTrialBalanceIndexRouteImport } from './routes/_authenticated/trial-balance/index'
import { Route as AuthenticatedTreasuryIndexRouteImport } from './routes/_authenticated/treasury/index'
import { Route as AuthenticatedTemplatesIndexRouteImport } from './routes/_authenticated/templates/index'
import { Route as AuthenticatedTaxToolsIndexRouteImport } from './routes/_authenticated/tax-tools/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedScenariosIndexRouteImport } from './routes/_authenticated/scenarios/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications/index'
import { Route as AuthenticatedNotesIndexRouteImport } from './routes/_authenticated/notes/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedIntelligenceIndexRouteImport } from './routes/_authenticated/intelligence/index'
import { Route as AuthenticatedInsightsIndexRouteImport } from './routes/_authenticated/insights/index'
import { Route as AuthenticatedImportsIndexRouteImport } from './routes/_authenticated/imports/index'
import { Route as AuthenticatedForecastingIndexRouteImport } from './routes/_authenticated/forecasting/index'
import { Route as AuthenticatedFixedAssetsIndexRouteImport } from './routes/_authenticated/fixed-assets/index'
import { Route as AuthenticatedFinancialsIndexRouteImport } from './routes/_authenticated/financials/index'
import { Route as AuthenticatedFinancialIndicatorsIndexRouteImport } from './routes/_authenticated/financial-indicators/index'
import { Route as AuthenticatedExecutiveIndexRouteImport } from './routes/_authenticated/executive/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCostsIndexRouteImport } from './routes/_authenticated/costs/index'
import { Route as AuthenticatedCopilotIndexRouteImport } from './routes/_authenticated/copilot/index'
import { Route as AuthenticatedControlIndexRouteImport } from './routes/_authenticated/control/index'
import { Route as AuthenticatedContractsIndexRouteImport } from './routes/_authenticated/contracts/index'
import { Route as AuthenticatedBoardIndexRouteImport } from './routes/_authenticated/board/index'
import { Route as AuthenticatedBanksIndexRouteImport } from './routes/_authenticated/banks/index'
import { Route as AuthenticatedAlertsIndexRouteImport } from './routes/_authenticated/alerts/index'
import { Route as AuthenticatedVendorsTopRouteImport } from './routes/_authenticated/vendors/top'
import { Route as AuthenticatedVendorsAgingRouteImport } from './routes/_authenticated/vendors/aging'
import { Route as AuthenticatedTreasuryForecastRouteImport } from './routes/_authenticated/treasury/forecast'
import { Route as AuthenticatedTasksTeamRouteImport } from './routes/_authenticated/tasks/team'
import { Route as AuthenticatedTasksIdRouteImport } from './routes/_authenticated/tasks/$id'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedSettingsRegionalRouteImport } from './routes/_authenticated/settings/regional'
import { Route as AuthenticatedSettingsPermissionsRouteImport } from './routes/_authenticated/settings/permissions'
import { Route as AuthenticatedSettingsApprovalsRouteImport } from './routes/_authenticated/settings/approvals'
import { Route as AuthenticatedReceivablesAgingRouteImport } from './routes/_authenticated/receivables/aging'
import { Route as AuthenticatedProjectsProgressRouteImport } from './routes/_authenticated/projects/progress'
import { Route as AuthenticatedIntelligenceVendorsRouteImport } from './routes/_authenticated/intelligence/vendors'
import { Route as AuthenticatedIntelligenceCustomersRouteImport } from './routes/_authenticated/intelligence/customers'
import { Route as AuthenticatedImportsUploadRouteImport } from './routes/_authenticated/imports/upload'
import { Route as AuthenticatedFinancialsKpisRouteImport } from './routes/_authenticated/financials/kpis'
import { Route as AuthenticatedFinancialsIncomeStatementRouteImport } from './routes/_authenticated/financials/income-statement'
import { Route as AuthenticatedFinancialsEquityRouteImport } from './routes/_authenticated/financials/equity'
import { Route as AuthenticatedFinancialsCashFlowRouteImport } from './routes/_authenticated/financials/cash-flow'
import { Route as AuthenticatedFinancialsBalanceSheetRouteImport } from './routes/_authenticated/financials/balance-sheet'
import { Route as AuthenticatedCustomersImportRouteImport } from './routes/_authenticated/customers/import'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers/$id'
import { Route as AuthenticatedControlProjectsRouteImport } from './routes/_authenticated/control/projects'
import { Route as AuthenticatedControlCostsRouteImport } from './routes/_authenticated/control/costs'
import { Route as AuthenticatedCashFlowMatrixRouteImport } from './routes/_authenticated/cash-flow/matrix'
import { Route as AuthenticatedVendorsStatementIdRouteImport } from './routes/_authenticated/vendors/statement.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrialBalanceIndexRoute =
  AuthenticatedTrialBalanceIndexRouteImport.update({
    id: '/trial-balance/',
    path: '/trial-balance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreasuryIndexRoute =
  AuthenticatedTreasuryIndexRouteImport.update({
    id: '/treasury/',
    path: '/treasury/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTemplatesIndexRoute =
  AuthenticatedTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTaxToolsIndexRoute =
  AuthenticatedTaxToolsIndexRouteImport.update({
    id: '/tax-tools/',
    path: '/tax-tools/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedScenariosIndexRoute =
  AuthenticatedScenariosIndexRouteImport.update({
    id: '/scenarios/',
    path: '/scenarios/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotesIndexRoute = AuthenticatedNotesIndexRouteImport.update({
  id: '/notes/',
  path: '/notes/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntelligenceIndexRoute =
  AuthenticatedIntelligenceIndexRouteImport.update({
    id: '/intelligence/',
    path: '/intelligence/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsIndexRoute =
  AuthenticatedInsightsIndexRouteImport.update({
    id: '/insights/',
    path: '/insights/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportsIndexRoute =
  AuthenticatedImportsIndexRouteImport.update({
    id: '/imports/',
    path: '/imports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedForecastingIndexRoute =
  AuthenticatedForecastingIndexRouteImport.update({
    id: '/forecasting/',
    path: '/forecasting/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFixedAssetsIndexRoute =
  AuthenticatedFixedAssetsIndexRouteImport.update({
    id: '/fixed-assets/',
    path: '/fixed-assets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsIndexRoute =
  AuthenticatedFinancialsIndexRouteImport.update({
    id: '/financials/',
    path: '/financials/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialIndicatorsIndexRoute =
  AuthenticatedFinancialIndicatorsIndexRouteImport.update({
    id: '/financial-indicators/',
    path: '/financial-indicators/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExecutiveIndexRoute =
  AuthenticatedExecutiveIndexRouteImport.update({
    id: '/executive/',
    path: '/executive/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsIndexRoute = AuthenticatedCostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopilotIndexRoute =
  AuthenticatedCopilotIndexRouteImport.update({
    id: '/copilot/',
    path: '/copilot/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedControlIndexRoute =
  AuthenticatedControlIndexRouteImport.update({
    id: '/control/',
    path: '/control/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContractsIndexRoute =
  AuthenticatedContractsIndexRouteImport.update({
    id: '/contracts/',
    path: '/contracts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBoardIndexRoute = AuthenticatedBoardIndexRouteImport.update({
  id: '/board/',
  path: '/board/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBanksIndexRoute = AuthenticatedBanksIndexRouteImport.update({
  id: '/banks/',
  path: '/banks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAlertsIndexRoute =
  AuthenticatedAlertsIndexRouteImport.update({
    id: '/alerts/',
    path: '/alerts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVendorsTopRoute = AuthenticatedVendorsTopRouteImport.update({
  id: '/vendors/top',
  path: '/vendors/top',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsAgingRoute =
  AuthenticatedVendorsAgingRouteImport.update({
    id: '/vendors/aging',
    path: '/vendors/aging',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreasuryForecastRoute =
  AuthenticatedTreasuryForecastRouteImport.update({
    id: '/treasury/forecast',
    path: '/treasury/forecast',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksTeamRoute = AuthenticatedTasksTeamRouteImport.update({
  id: '/tasks/team',
  path: '/tasks/team',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTasksIdRoute = AuthenticatedTasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRegionalRoute =
  AuthenticatedSettingsRegionalRouteImport.update({
    id: '/settings/regional',
    path: '/settings/regional',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsPermissionsRoute =
  AuthenticatedSettingsPermissionsRouteImport.update({
    id: '/settings/permissions',
    path: '/settings/permissions',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsApprovalsRoute =
  AuthenticatedSettingsApprovalsRouteImport.update({
    id: '/settings/approvals',
    path: '/settings/approvals',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceivablesAgingRoute =
  AuthenticatedReceivablesAgingRouteImport.update({
    id: '/receivables/aging',
    path: '/receivables/aging',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProgressRoute =
  AuthenticatedProjectsProgressRouteImport.update({
    id: '/projects/progress',
    path: '/projects/progress',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntelligenceVendorsRoute =
  AuthenticatedIntelligenceVendorsRouteImport.update({
    id: '/intelligence/vendors',
    path: '/intelligence/vendors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntelligenceCustomersRoute =
  AuthenticatedIntelligenceCustomersRouteImport.update({
    id: '/intelligence/customers',
    path: '/intelligence/customers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportsUploadRoute =
  AuthenticatedImportsUploadRouteImport.update({
    id: '/imports/upload',
    path: '/imports/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsKpisRoute =
  AuthenticatedFinancialsKpisRouteImport.update({
    id: '/financials/kpis',
    path: '/financials/kpis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsIncomeStatementRoute =
  AuthenticatedFinancialsIncomeStatementRouteImport.update({
    id: '/financials/income-statement',
    path: '/financials/income-statement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsEquityRoute =
  AuthenticatedFinancialsEquityRouteImport.update({
    id: '/financials/equity',
    path: '/financials/equity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsCashFlowRoute =
  AuthenticatedFinancialsCashFlowRouteImport.update({
    id: '/financials/cash-flow',
    path: '/financials/cash-flow',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsBalanceSheetRoute =
  AuthenticatedFinancialsBalanceSheetRouteImport.update({
    id: '/financials/balance-sheet',
    path: '/financials/balance-sheet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersImportRoute =
  AuthenticatedCustomersImportRouteImport.update({
    id: '/customers/import',
    path: '/customers/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedControlProjectsRoute =
  AuthenticatedControlProjectsRouteImport.update({
    id: '/control/projects',
    path: '/control/projects',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedControlCostsRoute =
  AuthenticatedControlCostsRouteImport.update({
    id: '/control/costs',
    path: '/control/costs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCashFlowMatrixRoute =
  AuthenticatedCashFlowMatrixRouteImport.update({
    id: '/cash-flow/matrix',
    path: '/cash-flow/matrix',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVendorsStatementIdRoute =
  AuthenticatedVendorsStatementIdRouteImport.update({
    id: '/vendors/statement/$id',
    path: '/vendors/statement/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cash-flow/matrix': typeof AuthenticatedCashFlowMatrixRoute
  '/control/costs': typeof AuthenticatedControlCostsRoute
  '/control/projects': typeof AuthenticatedControlProjectsRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/import': typeof AuthenticatedCustomersImportRoute
  '/financials/balance-sheet': typeof AuthenticatedFinancialsBalanceSheetRoute
  '/financials/cash-flow': typeof AuthenticatedFinancialsCashFlowRoute
  '/financials/equity': typeof AuthenticatedFinancialsEquityRoute
  '/financials/income-statement': typeof AuthenticatedFinancialsIncomeStatementRoute
  '/financials/kpis': typeof AuthenticatedFinancialsKpisRoute
  '/imports/upload': typeof AuthenticatedImportsUploadRoute
  '/intelligence/customers': typeof AuthenticatedIntelligenceCustomersRoute
  '/intelligence/vendors': typeof AuthenticatedIntelligenceVendorsRoute
  '/projects/progress': typeof AuthenticatedProjectsProgressRoute
  '/receivables/aging': typeof AuthenticatedReceivablesAgingRoute
  '/settings/approvals': typeof AuthenticatedSettingsApprovalsRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/regional': typeof AuthenticatedSettingsRegionalRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/team': typeof AuthenticatedTasksTeamRoute
  '/treasury/forecast': typeof AuthenticatedTreasuryForecastRoute
  '/vendors/aging': typeof AuthenticatedVendorsAgingRoute
  '/vendors/top': typeof AuthenticatedVendorsTopRoute
  '/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/banks/': typeof AuthenticatedBanksIndexRoute
  '/board/': typeof AuthenticatedBoardIndexRoute
  '/contracts/': typeof AuthenticatedContractsIndexRoute
  '/control/': typeof AuthenticatedControlIndexRoute
  '/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/costs/': typeof AuthenticatedCostsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/executive/': typeof AuthenticatedExecutiveIndexRoute
  '/financial-indicators/': typeof AuthenticatedFinancialIndicatorsIndexRoute
  '/financials/': typeof AuthenticatedFinancialsIndexRoute
  '/fixed-assets/': typeof AuthenticatedFixedAssetsIndexRoute
  '/forecasting/': typeof AuthenticatedForecastingIndexRoute
  '/imports/': typeof AuthenticatedImportsIndexRoute
  '/insights/': typeof AuthenticatedInsightsIndexRoute
  '/intelligence/': typeof AuthenticatedIntelligenceIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/notes/': typeof AuthenticatedNotesIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/scenarios/': typeof AuthenticatedScenariosIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/tax-tools/': typeof AuthenticatedTaxToolsIndexRoute
  '/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/treasury/': typeof AuthenticatedTreasuryIndexRoute
  '/trial-balance/': typeof AuthenticatedTrialBalanceIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/vendors/statement/$id': typeof AuthenticatedVendorsStatementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cash-flow/matrix': typeof AuthenticatedCashFlowMatrixRoute
  '/control/costs': typeof AuthenticatedControlCostsRoute
  '/control/projects': typeof AuthenticatedControlProjectsRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/import': typeof AuthenticatedCustomersImportRoute
  '/financials/balance-sheet': typeof AuthenticatedFinancialsBalanceSheetRoute
  '/financials/cash-flow': typeof AuthenticatedFinancialsCashFlowRoute
  '/financials/equity': typeof AuthenticatedFinancialsEquityRoute
  '/financials/income-statement': typeof AuthenticatedFinancialsIncomeStatementRoute
  '/financials/kpis': typeof AuthenticatedFinancialsKpisRoute
  '/imports/upload': typeof AuthenticatedImportsUploadRoute
  '/intelligence/customers': typeof AuthenticatedIntelligenceCustomersRoute
  '/intelligence/vendors': typeof AuthenticatedIntelligenceVendorsRoute
  '/projects/progress': typeof AuthenticatedProjectsProgressRoute
  '/receivables/aging': typeof AuthenticatedReceivablesAgingRoute
  '/settings/approvals': typeof AuthenticatedSettingsApprovalsRoute
  '/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/settings/regional': typeof AuthenticatedSettingsRegionalRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/tasks/team': typeof AuthenticatedTasksTeamRoute
  '/treasury/forecast': typeof AuthenticatedTreasuryForecastRoute
  '/vendors/aging': typeof AuthenticatedVendorsAgingRoute
  '/vendors/top': typeof AuthenticatedVendorsTopRoute
  '/alerts': typeof AuthenticatedAlertsIndexRoute
  '/banks': typeof AuthenticatedBanksIndexRoute
  '/board': typeof AuthenticatedBoardIndexRoute
  '/contracts': typeof AuthenticatedContractsIndexRoute
  '/control': typeof AuthenticatedControlIndexRoute
  '/copilot': typeof AuthenticatedCopilotIndexRoute
  '/costs': typeof AuthenticatedCostsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/executive': typeof AuthenticatedExecutiveIndexRoute
  '/financial-indicators': typeof AuthenticatedFinancialIndicatorsIndexRoute
  '/financials': typeof AuthenticatedFinancialsIndexRoute
  '/fixed-assets': typeof AuthenticatedFixedAssetsIndexRoute
  '/forecasting': typeof AuthenticatedForecastingIndexRoute
  '/imports': typeof AuthenticatedImportsIndexRoute
  '/insights': typeof AuthenticatedInsightsIndexRoute
  '/intelligence': typeof AuthenticatedIntelligenceIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/notes': typeof AuthenticatedNotesIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/scenarios': typeof AuthenticatedScenariosIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tax-tools': typeof AuthenticatedTaxToolsIndexRoute
  '/templates': typeof AuthenticatedTemplatesIndexRoute
  '/treasury': typeof AuthenticatedTreasuryIndexRoute
  '/trial-balance': typeof AuthenticatedTrialBalanceIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/vendors/statement/$id': typeof AuthenticatedVendorsStatementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/cash-flow/matrix': typeof AuthenticatedCashFlowMatrixRoute
  '/_authenticated/control/costs': typeof AuthenticatedControlCostsRoute
  '/_authenticated/control/projects': typeof AuthenticatedControlProjectsRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/customers/import': typeof AuthenticatedCustomersImportRoute
  '/_authenticated/financials/balance-sheet': typeof AuthenticatedFinancialsBalanceSheetRoute
  '/_authenticated/financials/cash-flow': typeof AuthenticatedFinancialsCashFlowRoute
  '/_authenticated/financials/equity': typeof AuthenticatedFinancialsEquityRoute
  '/_authenticated/financials/income-statement': typeof AuthenticatedFinancialsIncomeStatementRoute
  '/_authenticated/financials/kpis': typeof AuthenticatedFinancialsKpisRoute
  '/_authenticated/imports/upload': typeof AuthenticatedImportsUploadRoute
  '/_authenticated/intelligence/customers': typeof AuthenticatedIntelligenceCustomersRoute
  '/_authenticated/intelligence/vendors': typeof AuthenticatedIntelligenceVendorsRoute
  '/_authenticated/projects/progress': typeof AuthenticatedProjectsProgressRoute
  '/_authenticated/receivables/aging': typeof AuthenticatedReceivablesAgingRoute
  '/_authenticated/settings/approvals': typeof AuthenticatedSettingsApprovalsRoute
  '/_authenticated/settings/permissions': typeof AuthenticatedSettingsPermissionsRoute
  '/_authenticated/settings/regional': typeof AuthenticatedSettingsRegionalRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/tasks/$id': typeof AuthenticatedTasksIdRoute
  '/_authenticated/tasks/team': typeof AuthenticatedTasksTeamRoute
  '/_authenticated/treasury/forecast': typeof AuthenticatedTreasuryForecastRoute
  '/_authenticated/vendors/aging': typeof AuthenticatedVendorsAgingRoute
  '/_authenticated/vendors/top': typeof AuthenticatedVendorsTopRoute
  '/_authenticated/alerts/': typeof AuthenticatedAlertsIndexRoute
  '/_authenticated/banks/': typeof AuthenticatedBanksIndexRoute
  '/_authenticated/board/': typeof AuthenticatedBoardIndexRoute
  '/_authenticated/contracts/': typeof AuthenticatedContractsIndexRoute
  '/_authenticated/control/': typeof AuthenticatedControlIndexRoute
  '/_authenticated/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/_authenticated/costs/': typeof AuthenticatedCostsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/executive/': typeof AuthenticatedExecutiveIndexRoute
  '/_authenticated/financial-indicators/': typeof AuthenticatedFinancialIndicatorsIndexRoute
  '/_authenticated/financials/': typeof AuthenticatedFinancialsIndexRoute
  '/_authenticated/fixed-assets/': typeof AuthenticatedFixedAssetsIndexRoute
  '/_authenticated/forecasting/': typeof AuthenticatedForecastingIndexRoute
  '/_authenticated/imports/': typeof AuthenticatedImportsIndexRoute
  '/_authenticated/insights/': typeof AuthenticatedInsightsIndexRoute
  '/_authenticated/intelligence/': typeof AuthenticatedIntelligenceIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/notes/': typeof AuthenticatedNotesIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/scenarios/': typeof AuthenticatedScenariosIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tax-tools/': typeof AuthenticatedTaxToolsIndexRoute
  '/_authenticated/templates/': typeof AuthenticatedTemplatesIndexRoute
  '/_authenticated/treasury/': typeof AuthenticatedTreasuryIndexRoute
  '/_authenticated/trial-balance/': typeof AuthenticatedTrialBalanceIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/vendors/statement/$id': typeof AuthenticatedVendorsStatementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/cash-flow/matrix'
    | '/control/costs'
    | '/control/projects'
    | '/customers/$id'
    | '/customers/import'
    | '/financials/balance-sheet'
    | '/financials/cash-flow'
    | '/financials/equity'
    | '/financials/income-statement'
    | '/financials/kpis'
    | '/imports/upload'
    | '/intelligence/customers'
    | '/intelligence/vendors'
    | '/projects/progress'
    | '/receivables/aging'
    | '/settings/approvals'
    | '/settings/permissions'
    | '/settings/regional'
    | '/settings/users'
    | '/tasks/$id'
    | '/tasks/team'
    | '/treasury/forecast'
    | '/vendors/aging'
    | '/vendors/top'
    | '/alerts/'
    | '/banks/'
    | '/board/'
    | '/contracts/'
    | '/control/'
    | '/copilot/'
    | '/costs/'
    | '/customers/'
    | '/executive/'
    | '/financial-indicators/'
    | '/financials/'
    | '/fixed-assets/'
    | '/forecasting/'
    | '/imports/'
    | '/insights/'
    | '/intelligence/'
    | '/invoices/'
    | '/notes/'
    | '/notifications/'
    | '/projects/'
    | '/reports/'
    | '/scenarios/'
    | '/suppliers/'
    | '/tasks/'
    | '/tax-tools/'
    | '/templates/'
    | '/treasury/'
    | '/trial-balance/'
    | '/vendors/'
    | '/vendors/statement/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/dashboard'
    | '/cash-flow/matrix'
    | '/control/costs'
    | '/control/projects'
    | '/customers/$id'
    | '/customers/import'
    | '/financials/balance-sheet'
    | '/financials/cash-flow'
    | '/financials/equity'
    | '/financials/income-statement'
    | '/financials/kpis'
    | '/imports/upload'
    | '/intelligence/customers'
    | '/intelligence/vendors'
    | '/projects/progress'
    | '/receivables/aging'
    | '/settings/approvals'
    | '/settings/permissions'
    | '/settings/regional'
    | '/settings/users'
    | '/tasks/$id'
    | '/tasks/team'
    | '/treasury/forecast'
    | '/vendors/aging'
    | '/vendors/top'
    | '/alerts'
    | '/banks'
    | '/board'
    | '/contracts'
    | '/control'
    | '/copilot'
    | '/costs'
    | '/customers'
    | '/executive'
    | '/financial-indicators'
    | '/financials'
    | '/fixed-assets'
    | '/forecasting'
    | '/imports'
    | '/insights'
    | '/intelligence'
    | '/invoices'
    | '/notes'
    | '/notifications'
    | '/projects'
    | '/reports'
    | '/scenarios'
    | '/suppliers'
    | '/tasks'
    | '/tax-tools'
    | '/templates'
    | '/treasury'
    | '/trial-balance'
    | '/vendors'
    | '/vendors/statement/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/cash-flow/matrix'
    | '/_authenticated/control/costs'
    | '/_authenticated/control/projects'
    | '/_authenticated/customers/$id'
    | '/_authenticated/customers/import'
    | '/_authenticated/financials/balance-sheet'
    | '/_authenticated/financials/cash-flow'
    | '/_authenticated/financials/equity'
    | '/_authenticated/financials/income-statement'
    | '/_authenticated/financials/kpis'
    | '/_authenticated/imports/upload'
    | '/_authenticated/intelligence/customers'
    | '/_authenticated/intelligence/vendors'
    | '/_authenticated/projects/progress'
    | '/_authenticated/receivables/aging'
    | '/_authenticated/settings/approvals'
    | '/_authenticated/settings/permissions'
    | '/_authenticated/settings/regional'
    | '/_authenticated/settings/users'
    | '/_authenticated/tasks/$id'
    | '/_authenticated/tasks/team'
    | '/_authenticated/treasury/forecast'
    | '/_authenticated/vendors/aging'
    | '/_authenticated/vendors/top'
    | '/_authenticated/alerts/'
    | '/_authenticated/banks/'
    | '/_authenticated/board/'
    | '/_authenticated/contracts/'
    | '/_authenticated/control/'
    | '/_authenticated/copilot/'
    | '/_authenticated/costs/'
    | '/_authenticated/customers/'
    | '/_authenticated/executive/'
    | '/_authenticated/financial-indicators/'
    | '/_authenticated/financials/'
    | '/_authenticated/fixed-assets/'
    | '/_authenticated/forecasting/'
    | '/_authenticated/imports/'
    | '/_authenticated/insights/'
    | '/_authenticated/intelligence/'
    | '/_authenticated/invoices/'
    | '/_authenticated/notes/'
    | '/_authenticated/notifications/'
    | '/_authenticated/projects/'
    | '/_authenticated/reports/'
    | '/_authenticated/scenarios/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tax-tools/'
    | '/_authenticated/templates/'
    | '/_authenticated/treasury/'
    | '/_authenticated/trial-balance/'
    | '/_authenticated/vendors/'
    | '/_authenticated/vendors/statement/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trial-balance/': {
      id: '/_authenticated/trial-balance/'
      path: '/trial-balance'
      fullPath: '/trial-balance/'
      preLoaderRoute: typeof AuthenticatedTrialBalanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treasury/': {
      id: '/_authenticated/treasury/'
      path: '/treasury'
      fullPath: '/treasury/'
      preLoaderRoute: typeof AuthenticatedTreasuryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/templates/': {
      id: '/_authenticated/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof AuthenticatedTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tax-tools/': {
      id: '/_authenticated/tax-tools/'
      path: '/tax-tools'
      fullPath: '/tax-tools/'
      preLoaderRoute: typeof AuthenticatedTaxToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/scenarios/': {
      id: '/_authenticated/scenarios/'
      path: '/scenarios'
      fullPath: '/scenarios/'
      preLoaderRoute: typeof AuthenticatedScenariosIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notes/': {
      id: '/_authenticated/notes/'
      path: '/notes'
      fullPath: '/notes/'
      preLoaderRoute: typeof AuthenticatedNotesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence/': {
      id: '/_authenticated/intelligence/'
      path: '/intelligence'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof AuthenticatedIntelligenceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/': {
      id: '/_authenticated/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof AuthenticatedInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imports/': {
      id: '/_authenticated/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof AuthenticatedImportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/forecasting/': {
      id: '/_authenticated/forecasting/'
      path: '/forecasting'
      fullPath: '/forecasting/'
      preLoaderRoute: typeof AuthenticatedForecastingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fixed-assets/': {
      id: '/_authenticated/fixed-assets/'
      path: '/fixed-assets'
      fullPath: '/fixed-assets/'
      preLoaderRoute: typeof AuthenticatedFixedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/': {
      id: '/_authenticated/financials/'
      path: '/financials'
      fullPath: '/financials/'
      preLoaderRoute: typeof AuthenticatedFinancialsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial-indicators/': {
      id: '/_authenticated/financial-indicators/'
      path: '/financial-indicators'
      fullPath: '/financial-indicators/'
      preLoaderRoute: typeof AuthenticatedFinancialIndicatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/executive/': {
      id: '/_authenticated/executive/'
      path: '/executive'
      fullPath: '/executive/'
      preLoaderRoute: typeof AuthenticatedExecutiveIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs/': {
      id: '/_authenticated/costs/'
      path: '/costs'
      fullPath: '/costs/'
      preLoaderRoute: typeof AuthenticatedCostsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copilot/': {
      id: '/_authenticated/copilot/'
      path: '/copilot'
      fullPath: '/copilot/'
      preLoaderRoute: typeof AuthenticatedCopilotIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control/': {
      id: '/_authenticated/control/'
      path: '/control'
      fullPath: '/control/'
      preLoaderRoute: typeof AuthenticatedControlIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contracts/': {
      id: '/_authenticated/contracts/'
      path: '/contracts'
      fullPath: '/contracts/'
      preLoaderRoute: typeof AuthenticatedContractsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/board/': {
      id: '/_authenticated/board/'
      path: '/board'
      fullPath: '/board/'
      preLoaderRoute: typeof AuthenticatedBoardIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banks/': {
      id: '/_authenticated/banks/'
      path: '/banks'
      fullPath: '/banks/'
      preLoaderRoute: typeof AuthenticatedBanksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/alerts/': {
      id: '/_authenticated/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AuthenticatedAlertsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/top': {
      id: '/_authenticated/vendors/top'
      path: '/vendors/top'
      fullPath: '/vendors/top'
      preLoaderRoute: typeof AuthenticatedVendorsTopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/aging': {
      id: '/_authenticated/vendors/aging'
      path: '/vendors/aging'
      fullPath: '/vendors/aging'
      preLoaderRoute: typeof AuthenticatedVendorsAgingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treasury/forecast': {
      id: '/_authenticated/treasury/forecast'
      path: '/treasury/forecast'
      fullPath: '/treasury/forecast'
      preLoaderRoute: typeof AuthenticatedTreasuryForecastRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/team': {
      id: '/_authenticated/tasks/team'
      path: '/tasks/team'
      fullPath: '/tasks/team'
      preLoaderRoute: typeof AuthenticatedTasksTeamRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/$id': {
      id: '/_authenticated/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof AuthenticatedTasksIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/regional': {
      id: '/_authenticated/settings/regional'
      path: '/settings/regional'
      fullPath: '/settings/regional'
      preLoaderRoute: typeof AuthenticatedSettingsRegionalRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/permissions': {
      id: '/_authenticated/settings/permissions'
      path: '/settings/permissions'
      fullPath: '/settings/permissions'
      preLoaderRoute: typeof AuthenticatedSettingsPermissionsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/approvals': {
      id: '/_authenticated/settings/approvals'
      path: '/settings/approvals'
      fullPath: '/settings/approvals'
      preLoaderRoute: typeof AuthenticatedSettingsApprovalsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receivables/aging': {
      id: '/_authenticated/receivables/aging'
      path: '/receivables/aging'
      fullPath: '/receivables/aging'
      preLoaderRoute: typeof AuthenticatedReceivablesAgingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/progress': {
      id: '/_authenticated/projects/progress'
      path: '/projects/progress'
      fullPath: '/projects/progress'
      preLoaderRoute: typeof AuthenticatedProjectsProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence/vendors': {
      id: '/_authenticated/intelligence/vendors'
      path: '/intelligence/vendors'
      fullPath: '/intelligence/vendors'
      preLoaderRoute: typeof AuthenticatedIntelligenceVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence/customers': {
      id: '/_authenticated/intelligence/customers'
      path: '/intelligence/customers'
      fullPath: '/intelligence/customers'
      preLoaderRoute: typeof AuthenticatedIntelligenceCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imports/upload': {
      id: '/_authenticated/imports/upload'
      path: '/imports/upload'
      fullPath: '/imports/upload'
      preLoaderRoute: typeof AuthenticatedImportsUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/kpis': {
      id: '/_authenticated/financials/kpis'
      path: '/financials/kpis'
      fullPath: '/financials/kpis'
      preLoaderRoute: typeof AuthenticatedFinancialsKpisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/income-statement': {
      id: '/_authenticated/financials/income-statement'
      path: '/financials/income-statement'
      fullPath: '/financials/income-statement'
      preLoaderRoute: typeof AuthenticatedFinancialsIncomeStatementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/equity': {
      id: '/_authenticated/financials/equity'
      path: '/financials/equity'
      fullPath: '/financials/equity'
      preLoaderRoute: typeof AuthenticatedFinancialsEquityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/cash-flow': {
      id: '/_authenticated/financials/cash-flow'
      path: '/financials/cash-flow'
      fullPath: '/financials/cash-flow'
      preLoaderRoute: typeof AuthenticatedFinancialsCashFlowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/balance-sheet': {
      id: '/_authenticated/financials/balance-sheet'
      path: '/financials/balance-sheet'
      fullPath: '/financials/balance-sheet'
      preLoaderRoute: typeof AuthenticatedFinancialsBalanceSheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/import': {
      id: '/_authenticated/customers/import'
      path: '/customers/import'
      fullPath: '/customers/import'
      preLoaderRoute: typeof AuthenticatedCustomersImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control/projects': {
      id: '/_authenticated/control/projects'
      path: '/control/projects'
      fullPath: '/control/projects'
      preLoaderRoute: typeof AuthenticatedControlProjectsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/control/costs': {
      id: '/_authenticated/control/costs'
      path: '/control/costs'
      fullPath: '/control/costs'
      preLoaderRoute: typeof AuthenticatedControlCostsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cash-flow/matrix': {
      id: '/_authenticated/cash-flow/matrix'
      path: '/cash-flow/matrix'
      fullPath: '/cash-flow/matrix'
      preLoaderRoute: typeof AuthenticatedCashFlowMatrixRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/statement/$id': {
      id: '/_authenticated/vendors/statement/$id'
      path: '/vendors/statement/$id'
      fullPath: '/vendors/statement/$id'
      preLoaderRoute: typeof AuthenticatedVendorsStatementIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCashFlowMatrixRoute: typeof AuthenticatedCashFlowMatrixRoute
  AuthenticatedControlCostsRoute: typeof AuthenticatedControlCostsRoute
  AuthenticatedControlProjectsRoute: typeof AuthenticatedControlProjectsRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersImportRoute: typeof AuthenticatedCustomersImportRoute
  AuthenticatedFinancialsBalanceSheetRoute: typeof AuthenticatedFinancialsBalanceSheetRoute
  AuthenticatedFinancialsCashFlowRoute: typeof AuthenticatedFinancialsCashFlowRoute
  AuthenticatedFinancialsEquityRoute: typeof AuthenticatedFinancialsEquityRoute
  AuthenticatedFinancialsIncomeStatementRoute: typeof AuthenticatedFinancialsIncomeStatementRoute
  AuthenticatedFinancialsKpisRoute: typeof AuthenticatedFinancialsKpisRoute
  AuthenticatedImportsUploadRoute: typeof AuthenticatedImportsUploadRoute
  AuthenticatedIntelligenceCustomersRoute: typeof AuthenticatedIntelligenceCustomersRoute
  AuthenticatedIntelligenceVendorsRoute: typeof AuthenticatedIntelligenceVendorsRoute
  AuthenticatedProjectsProgressRoute: typeof AuthenticatedProjectsProgressRoute
  AuthenticatedReceivablesAgingRoute: typeof AuthenticatedReceivablesAgingRoute
  AuthenticatedSettingsApprovalsRoute: typeof AuthenticatedSettingsApprovalsRoute
  AuthenticatedSettingsPermissionsRoute: typeof AuthenticatedSettingsPermissionsRoute
  AuthenticatedSettingsRegionalRoute: typeof AuthenticatedSettingsRegionalRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedTasksIdRoute: typeof AuthenticatedTasksIdRoute
  AuthenticatedTasksTeamRoute: typeof AuthenticatedTasksTeamRoute
  AuthenticatedTreasuryForecastRoute: typeof AuthenticatedTreasuryForecastRoute
  AuthenticatedVendorsAgingRoute: typeof AuthenticatedVendorsAgingRoute
  AuthenticatedVendorsTopRoute: typeof AuthenticatedVendorsTopRoute
  AuthenticatedAlertsIndexRoute: typeof AuthenticatedAlertsIndexRoute
  AuthenticatedBanksIndexRoute: typeof AuthenticatedBanksIndexRoute
  AuthenticatedBoardIndexRoute: typeof AuthenticatedBoardIndexRoute
  AuthenticatedContractsIndexRoute: typeof AuthenticatedContractsIndexRoute
  AuthenticatedControlIndexRoute: typeof AuthenticatedControlIndexRoute
  AuthenticatedCopilotIndexRoute: typeof AuthenticatedCopilotIndexRoute
  AuthenticatedCostsIndexRoute: typeof AuthenticatedCostsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedExecutiveIndexRoute: typeof AuthenticatedExecutiveIndexRoute
  AuthenticatedFinancialIndicatorsIndexRoute: typeof AuthenticatedFinancialIndicatorsIndexRoute
  AuthenticatedFinancialsIndexRoute: typeof AuthenticatedFinancialsIndexRoute
  AuthenticatedFixedAssetsIndexRoute: typeof AuthenticatedFixedAssetsIndexRoute
  AuthenticatedForecastingIndexRoute: typeof AuthenticatedForecastingIndexRoute
  AuthenticatedImportsIndexRoute: typeof AuthenticatedImportsIndexRoute
  AuthenticatedInsightsIndexRoute: typeof AuthenticatedInsightsIndexRoute
  AuthenticatedIntelligenceIndexRoute: typeof AuthenticatedIntelligenceIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedNotesIndexRoute: typeof AuthenticatedNotesIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedScenariosIndexRoute: typeof AuthenticatedScenariosIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTaxToolsIndexRoute: typeof AuthenticatedTaxToolsIndexRoute
  AuthenticatedTemplatesIndexRoute: typeof AuthenticatedTemplatesIndexRoute
  AuthenticatedTreasuryIndexRoute: typeof AuthenticatedTreasuryIndexRoute
  AuthenticatedTrialBalanceIndexRoute: typeof AuthenticatedTrialBalanceIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedVendorsStatementIdRoute: typeof AuthenticatedVendorsStatementIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCashFlowMatrixRoute: AuthenticatedCashFlowMatrixRoute,
  AuthenticatedControlCostsRoute: AuthenticatedControlCostsRoute,
  AuthenticatedControlProjectsRoute: AuthenticatedControlProjectsRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedCustomersImportRoute: AuthenticatedCustomersImportRoute,
  AuthenticatedFinancialsBalanceSheetRoute:
    AuthenticatedFinancialsBalanceSheetRoute,
  AuthenticatedFinancialsCashFlowRoute: AuthenticatedFinancialsCashFlowRoute,
  AuthenticatedFinancialsEquityRoute: AuthenticatedFinancialsEquityRoute,
  AuthenticatedFinancialsIncomeStatementRoute:
    AuthenticatedFinancialsIncomeStatementRoute,
  AuthenticatedFinancialsKpisRoute: AuthenticatedFinancialsKpisRoute,
  AuthenticatedImportsUploadRoute: AuthenticatedImportsUploadRoute,
  AuthenticatedIntelligenceCustomersRoute:
    AuthenticatedIntelligenceCustomersRoute,
  AuthenticatedIntelligenceVendorsRoute: AuthenticatedIntelligenceVendorsRoute,
  AuthenticatedProjectsProgressRoute: AuthenticatedProjectsProgressRoute,
  AuthenticatedReceivablesAgingRoute: AuthenticatedReceivablesAgingRoute,
  AuthenticatedSettingsApprovalsRoute: AuthenticatedSettingsApprovalsRoute,
  AuthenticatedSettingsPermissionsRoute: AuthenticatedSettingsPermissionsRoute,
  AuthenticatedSettingsRegionalRoute: AuthenticatedSettingsRegionalRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedTasksIdRoute: AuthenticatedTasksIdRoute,
  AuthenticatedTasksTeamRoute: AuthenticatedTasksTeamRoute,
  AuthenticatedTreasuryForecastRoute: AuthenticatedTreasuryForecastRoute,
  AuthenticatedVendorsAgingRoute: AuthenticatedVendorsAgingRoute,
  AuthenticatedVendorsTopRoute: AuthenticatedVendorsTopRoute,
  AuthenticatedAlertsIndexRoute: AuthenticatedAlertsIndexRoute,
  AuthenticatedBanksIndexRoute: AuthenticatedBanksIndexRoute,
  AuthenticatedBoardIndexRoute: AuthenticatedBoardIndexRoute,
  AuthenticatedContractsIndexRoute: AuthenticatedContractsIndexRoute,
  AuthenticatedControlIndexRoute: AuthenticatedControlIndexRoute,
  AuthenticatedCopilotIndexRoute: AuthenticatedCopilotIndexRoute,
  AuthenticatedCostsIndexRoute: AuthenticatedCostsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedExecutiveIndexRoute: AuthenticatedExecutiveIndexRoute,
  AuthenticatedFinancialIndicatorsIndexRoute:
    AuthenticatedFinancialIndicatorsIndexRoute,
  AuthenticatedFinancialsIndexRoute: AuthenticatedFinancialsIndexRoute,
  AuthenticatedFixedAssetsIndexRoute: AuthenticatedFixedAssetsIndexRoute,
  AuthenticatedForecastingIndexRoute: AuthenticatedForecastingIndexRoute,
  AuthenticatedImportsIndexRoute: AuthenticatedImportsIndexRoute,
  AuthenticatedInsightsIndexRoute: AuthenticatedInsightsIndexRoute,
  AuthenticatedIntelligenceIndexRoute: AuthenticatedIntelligenceIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedNotesIndexRoute: AuthenticatedNotesIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedScenariosIndexRoute: AuthenticatedScenariosIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTaxToolsIndexRoute: AuthenticatedTaxToolsIndexRoute,
  AuthenticatedTemplatesIndexRoute: AuthenticatedTemplatesIndexRoute,
  AuthenticatedTreasuryIndexRoute: AuthenticatedTreasuryIndexRoute,
  AuthenticatedTrialBalanceIndexRoute: AuthenticatedTrialBalanceIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedVendorsStatementIdRoute: AuthenticatedVendorsStatementIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
