/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedVendorsIndexRouteImport } from './routes/_authenticated/vendors/index'
import { Route as AuthenticatedTrialBalanceIndexRouteImport } from './routes/_authenticated/trial-balance/index'
import { Route as AuthenticatedTreasuryIndexRouteImport } from './routes/_authenticated/treasury/index'
import { Route as AuthenticatedTaxToolsIndexRouteImport } from './routes/_authenticated/tax-tools/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSuppliersIndexRouteImport } from './routes/_authenticated/suppliers/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedProjectsIndexRouteImport } from './routes/_authenticated/projects/index'
import { Route as AuthenticatedInvoicesIndexRouteImport } from './routes/_authenticated/invoices/index'
import { Route as AuthenticatedIntelligenceIndexRouteImport } from './routes/_authenticated/intelligence/index'
import { Route as AuthenticatedInsightsIndexRouteImport } from './routes/_authenticated/insights/index'
import { Route as AuthenticatedImportsIndexRouteImport } from './routes/_authenticated/imports/index'
import { Route as AuthenticatedFixedAssetsIndexRouteImport } from './routes/_authenticated/fixed-assets/index'
import { Route as AuthenticatedFinancialsIndexRouteImport } from './routes/_authenticated/financials/index'
import { Route as AuthenticatedFinancialIndicatorsIndexRouteImport } from './routes/_authenticated/financial-indicators/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedCostsIndexRouteImport } from './routes/_authenticated/costs/index'
import { Route as AuthenticatedCopilotIndexRouteImport } from './routes/_authenticated/copilot/index'
import { Route as AuthenticatedBanksIndexRouteImport } from './routes/_authenticated/banks/index'
import { Route as AuthenticatedVendorsTopRouteImport } from './routes/_authenticated/vendors/top'
import { Route as AuthenticatedVendorsAgingRouteImport } from './routes/_authenticated/vendors/aging'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'
import { Route as AuthenticatedReceivablesAgingRouteImport } from './routes/_authenticated/receivables/aging'
import { Route as AuthenticatedProjectsProgressRouteImport } from './routes/_authenticated/projects/progress'
import { Route as AuthenticatedIntelligenceVendorsRouteImport } from './routes/_authenticated/intelligence/vendors'
import { Route as AuthenticatedIntelligenceCustomersRouteImport } from './routes/_authenticated/intelligence/customers'
import { Route as AuthenticatedImportsUploadRouteImport } from './routes/_authenticated/imports/upload'
import { Route as AuthenticatedFinancialsKpisRouteImport } from './routes/_authenticated/financials/kpis'
import { Route as AuthenticatedFinancialsIncomeStatementRouteImport } from './routes/_authenticated/financials/income-statement'
import { Route as AuthenticatedFinancialsEquityRouteImport } from './routes/_authenticated/financials/equity'
import { Route as AuthenticatedFinancialsCashFlowRouteImport } from './routes/_authenticated/financials/cash-flow'
import { Route as AuthenticatedFinancialsBalanceSheetRouteImport } from './routes/_authenticated/financials/balance-sheet'
import { Route as AuthenticatedCustomersImportRouteImport } from './routes/_authenticated/customers/import'
import { Route as AuthenticatedCustomersIdRouteImport } from './routes/_authenticated/customers/$id'
import { Route as AuthenticatedCashFlowMatrixRouteImport } from './routes/_authenticated/cash-flow/matrix'
import { Route as AuthenticatedVendorsStatementIdRouteImport } from './routes/_authenticated/vendors/statement.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsIndexRoute =
  AuthenticatedVendorsIndexRouteImport.update({
    id: '/vendors/',
    path: '/vendors/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTrialBalanceIndexRoute =
  AuthenticatedTrialBalanceIndexRouteImport.update({
    id: '/trial-balance/',
    path: '/trial-balance/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTreasuryIndexRoute =
  AuthenticatedTreasuryIndexRouteImport.update({
    id: '/treasury/',
    path: '/treasury/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTaxToolsIndexRoute =
  AuthenticatedTaxToolsIndexRouteImport.update({
    id: '/tax-tools/',
    path: '/tax-tools/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSuppliersIndexRoute =
  AuthenticatedSuppliersIndexRouteImport.update({
    id: '/suppliers/',
    path: '/suppliers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsIndexRoute =
  AuthenticatedProjectsIndexRouteImport.update({
    id: '/projects/',
    path: '/projects/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInvoicesIndexRoute =
  AuthenticatedInvoicesIndexRouteImport.update({
    id: '/invoices/',
    path: '/invoices/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntelligenceIndexRoute =
  AuthenticatedIntelligenceIndexRouteImport.update({
    id: '/intelligence/',
    path: '/intelligence/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInsightsIndexRoute =
  AuthenticatedInsightsIndexRouteImport.update({
    id: '/insights/',
    path: '/insights/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportsIndexRoute =
  AuthenticatedImportsIndexRouteImport.update({
    id: '/imports/',
    path: '/imports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFixedAssetsIndexRoute =
  AuthenticatedFixedAssetsIndexRouteImport.update({
    id: '/fixed-assets/',
    path: '/fixed-assets/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsIndexRoute =
  AuthenticatedFinancialsIndexRouteImport.update({
    id: '/financials/',
    path: '/financials/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialIndicatorsIndexRoute =
  AuthenticatedFinancialIndicatorsIndexRouteImport.update({
    id: '/financial-indicators/',
    path: '/financial-indicators/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCostsIndexRoute = AuthenticatedCostsIndexRouteImport.update({
  id: '/costs/',
  path: '/costs/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCopilotIndexRoute =
  AuthenticatedCopilotIndexRouteImport.update({
    id: '/copilot/',
    path: '/copilot/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBanksIndexRoute = AuthenticatedBanksIndexRouteImport.update({
  id: '/banks/',
  path: '/banks/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsTopRoute = AuthenticatedVendorsTopRouteImport.update({
  id: '/vendors/top',
  path: '/vendors/top',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedVendorsAgingRoute =
  AuthenticatedVendorsAgingRouteImport.update({
    id: '/vendors/aging',
    path: '/vendors/aging',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReceivablesAgingRoute =
  AuthenticatedReceivablesAgingRouteImport.update({
    id: '/receivables/aging',
    path: '/receivables/aging',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProjectsProgressRoute =
  AuthenticatedProjectsProgressRouteImport.update({
    id: '/projects/progress',
    path: '/projects/progress',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntelligenceVendorsRoute =
  AuthenticatedIntelligenceVendorsRouteImport.update({
    id: '/intelligence/vendors',
    path: '/intelligence/vendors',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntelligenceCustomersRoute =
  AuthenticatedIntelligenceCustomersRouteImport.update({
    id: '/intelligence/customers',
    path: '/intelligence/customers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedImportsUploadRoute =
  AuthenticatedImportsUploadRouteImport.update({
    id: '/imports/upload',
    path: '/imports/upload',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsKpisRoute =
  AuthenticatedFinancialsKpisRouteImport.update({
    id: '/financials/kpis',
    path: '/financials/kpis',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsIncomeStatementRoute =
  AuthenticatedFinancialsIncomeStatementRouteImport.update({
    id: '/financials/income-statement',
    path: '/financials/income-statement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsEquityRoute =
  AuthenticatedFinancialsEquityRouteImport.update({
    id: '/financials/equity',
    path: '/financials/equity',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsCashFlowRoute =
  AuthenticatedFinancialsCashFlowRouteImport.update({
    id: '/financials/cash-flow',
    path: '/financials/cash-flow',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFinancialsBalanceSheetRoute =
  AuthenticatedFinancialsBalanceSheetRouteImport.update({
    id: '/financials/balance-sheet',
    path: '/financials/balance-sheet',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersImportRoute =
  AuthenticatedCustomersImportRouteImport.update({
    id: '/customers/import',
    path: '/customers/import',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIdRoute =
  AuthenticatedCustomersIdRouteImport.update({
    id: '/customers/$id',
    path: '/customers/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCashFlowMatrixRoute =
  AuthenticatedCashFlowMatrixRouteImport.update({
    id: '/cash-flow/matrix',
    path: '/cash-flow/matrix',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedVendorsStatementIdRoute =
  AuthenticatedVendorsStatementIdRouteImport.update({
    id: '/vendors/statement/$id',
    path: '/vendors/statement/$id',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cash-flow/matrix': typeof AuthenticatedCashFlowMatrixRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/import': typeof AuthenticatedCustomersImportRoute
  '/financials/balance-sheet': typeof AuthenticatedFinancialsBalanceSheetRoute
  '/financials/cash-flow': typeof AuthenticatedFinancialsCashFlowRoute
  '/financials/equity': typeof AuthenticatedFinancialsEquityRoute
  '/financials/income-statement': typeof AuthenticatedFinancialsIncomeStatementRoute
  '/financials/kpis': typeof AuthenticatedFinancialsKpisRoute
  '/imports/upload': typeof AuthenticatedImportsUploadRoute
  '/intelligence/customers': typeof AuthenticatedIntelligenceCustomersRoute
  '/intelligence/vendors': typeof AuthenticatedIntelligenceVendorsRoute
  '/projects/progress': typeof AuthenticatedProjectsProgressRoute
  '/receivables/aging': typeof AuthenticatedReceivablesAgingRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/vendors/aging': typeof AuthenticatedVendorsAgingRoute
  '/vendors/top': typeof AuthenticatedVendorsTopRoute
  '/banks/': typeof AuthenticatedBanksIndexRoute
  '/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/costs/': typeof AuthenticatedCostsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/financial-indicators/': typeof AuthenticatedFinancialIndicatorsIndexRoute
  '/financials/': typeof AuthenticatedFinancialsIndexRoute
  '/fixed-assets/': typeof AuthenticatedFixedAssetsIndexRoute
  '/imports/': typeof AuthenticatedImportsIndexRoute
  '/insights/': typeof AuthenticatedInsightsIndexRoute
  '/intelligence/': typeof AuthenticatedIntelligenceIndexRoute
  '/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/projects/': typeof AuthenticatedProjectsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/tax-tools/': typeof AuthenticatedTaxToolsIndexRoute
  '/treasury/': typeof AuthenticatedTreasuryIndexRoute
  '/trial-balance/': typeof AuthenticatedTrialBalanceIndexRoute
  '/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/vendors/statement/$id': typeof AuthenticatedVendorsStatementIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/cash-flow/matrix': typeof AuthenticatedCashFlowMatrixRoute
  '/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/customers/import': typeof AuthenticatedCustomersImportRoute
  '/financials/balance-sheet': typeof AuthenticatedFinancialsBalanceSheetRoute
  '/financials/cash-flow': typeof AuthenticatedFinancialsCashFlowRoute
  '/financials/equity': typeof AuthenticatedFinancialsEquityRoute
  '/financials/income-statement': typeof AuthenticatedFinancialsIncomeStatementRoute
  '/financials/kpis': typeof AuthenticatedFinancialsKpisRoute
  '/imports/upload': typeof AuthenticatedImportsUploadRoute
  '/intelligence/customers': typeof AuthenticatedIntelligenceCustomersRoute
  '/intelligence/vendors': typeof AuthenticatedIntelligenceVendorsRoute
  '/projects/progress': typeof AuthenticatedProjectsProgressRoute
  '/receivables/aging': typeof AuthenticatedReceivablesAgingRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/vendors/aging': typeof AuthenticatedVendorsAgingRoute
  '/vendors/top': typeof AuthenticatedVendorsTopRoute
  '/banks': typeof AuthenticatedBanksIndexRoute
  '/copilot': typeof AuthenticatedCopilotIndexRoute
  '/costs': typeof AuthenticatedCostsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/financial-indicators': typeof AuthenticatedFinancialIndicatorsIndexRoute
  '/financials': typeof AuthenticatedFinancialsIndexRoute
  '/fixed-assets': typeof AuthenticatedFixedAssetsIndexRoute
  '/imports': typeof AuthenticatedImportsIndexRoute
  '/insights': typeof AuthenticatedInsightsIndexRoute
  '/intelligence': typeof AuthenticatedIntelligenceIndexRoute
  '/invoices': typeof AuthenticatedInvoicesIndexRoute
  '/projects': typeof AuthenticatedProjectsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/suppliers': typeof AuthenticatedSuppliersIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tax-tools': typeof AuthenticatedTaxToolsIndexRoute
  '/treasury': typeof AuthenticatedTreasuryIndexRoute
  '/trial-balance': typeof AuthenticatedTrialBalanceIndexRoute
  '/vendors': typeof AuthenticatedVendorsIndexRoute
  '/vendors/statement/$id': typeof AuthenticatedVendorsStatementIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/cash-flow/matrix': typeof AuthenticatedCashFlowMatrixRoute
  '/_authenticated/customers/$id': typeof AuthenticatedCustomersIdRoute
  '/_authenticated/customers/import': typeof AuthenticatedCustomersImportRoute
  '/_authenticated/financials/balance-sheet': typeof AuthenticatedFinancialsBalanceSheetRoute
  '/_authenticated/financials/cash-flow': typeof AuthenticatedFinancialsCashFlowRoute
  '/_authenticated/financials/equity': typeof AuthenticatedFinancialsEquityRoute
  '/_authenticated/financials/income-statement': typeof AuthenticatedFinancialsIncomeStatementRoute
  '/_authenticated/financials/kpis': typeof AuthenticatedFinancialsKpisRoute
  '/_authenticated/imports/upload': typeof AuthenticatedImportsUploadRoute
  '/_authenticated/intelligence/customers': typeof AuthenticatedIntelligenceCustomersRoute
  '/_authenticated/intelligence/vendors': typeof AuthenticatedIntelligenceVendorsRoute
  '/_authenticated/projects/progress': typeof AuthenticatedProjectsProgressRoute
  '/_authenticated/receivables/aging': typeof AuthenticatedReceivablesAgingRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
  '/_authenticated/vendors/aging': typeof AuthenticatedVendorsAgingRoute
  '/_authenticated/vendors/top': typeof AuthenticatedVendorsTopRoute
  '/_authenticated/banks/': typeof AuthenticatedBanksIndexRoute
  '/_authenticated/copilot/': typeof AuthenticatedCopilotIndexRoute
  '/_authenticated/costs/': typeof AuthenticatedCostsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/financial-indicators/': typeof AuthenticatedFinancialIndicatorsIndexRoute
  '/_authenticated/financials/': typeof AuthenticatedFinancialsIndexRoute
  '/_authenticated/fixed-assets/': typeof AuthenticatedFixedAssetsIndexRoute
  '/_authenticated/imports/': typeof AuthenticatedImportsIndexRoute
  '/_authenticated/insights/': typeof AuthenticatedInsightsIndexRoute
  '/_authenticated/intelligence/': typeof AuthenticatedIntelligenceIndexRoute
  '/_authenticated/invoices/': typeof AuthenticatedInvoicesIndexRoute
  '/_authenticated/projects/': typeof AuthenticatedProjectsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/suppliers/': typeof AuthenticatedSuppliersIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tax-tools/': typeof AuthenticatedTaxToolsIndexRoute
  '/_authenticated/treasury/': typeof AuthenticatedTreasuryIndexRoute
  '/_authenticated/trial-balance/': typeof AuthenticatedTrialBalanceIndexRoute
  '/_authenticated/vendors/': typeof AuthenticatedVendorsIndexRoute
  '/_authenticated/vendors/statement/$id': typeof AuthenticatedVendorsStatementIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/dashboard'
    | '/cash-flow/matrix'
    | '/customers/$id'
    | '/customers/import'
    | '/financials/balance-sheet'
    | '/financials/cash-flow'
    | '/financials/equity'
    | '/financials/income-statement'
    | '/financials/kpis'
    | '/imports/upload'
    | '/intelligence/customers'
    | '/intelligence/vendors'
    | '/projects/progress'
    | '/receivables/aging'
    | '/settings/users'
    | '/vendors/aging'
    | '/vendors/top'
    | '/banks/'
    | '/copilot/'
    | '/costs/'
    | '/customers/'
    | '/financial-indicators/'
    | '/financials/'
    | '/fixed-assets/'
    | '/imports/'
    | '/insights/'
    | '/intelligence/'
    | '/invoices/'
    | '/projects/'
    | '/reports/'
    | '/suppliers/'
    | '/tasks/'
    | '/tax-tools/'
    | '/treasury/'
    | '/trial-balance/'
    | '/vendors/'
    | '/vendors/statement/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/dashboard'
    | '/cash-flow/matrix'
    | '/customers/$id'
    | '/customers/import'
    | '/financials/balance-sheet'
    | '/financials/cash-flow'
    | '/financials/equity'
    | '/financials/income-statement'
    | '/financials/kpis'
    | '/imports/upload'
    | '/intelligence/customers'
    | '/intelligence/vendors'
    | '/projects/progress'
    | '/receivables/aging'
    | '/settings/users'
    | '/vendors/aging'
    | '/vendors/top'
    | '/banks'
    | '/copilot'
    | '/costs'
    | '/customers'
    | '/financial-indicators'
    | '/financials'
    | '/fixed-assets'
    | '/imports'
    | '/insights'
    | '/intelligence'
    | '/invoices'
    | '/projects'
    | '/reports'
    | '/suppliers'
    | '/tasks'
    | '/tax-tools'
    | '/treasury'
    | '/trial-balance'
    | '/vendors'
    | '/vendors/statement/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/dashboard'
    | '/_authenticated/cash-flow/matrix'
    | '/_authenticated/customers/$id'
    | '/_authenticated/customers/import'
    | '/_authenticated/financials/balance-sheet'
    | '/_authenticated/financials/cash-flow'
    | '/_authenticated/financials/equity'
    | '/_authenticated/financials/income-statement'
    | '/_authenticated/financials/kpis'
    | '/_authenticated/imports/upload'
    | '/_authenticated/intelligence/customers'
    | '/_authenticated/intelligence/vendors'
    | '/_authenticated/projects/progress'
    | '/_authenticated/receivables/aging'
    | '/_authenticated/settings/users'
    | '/_authenticated/vendors/aging'
    | '/_authenticated/vendors/top'
    | '/_authenticated/banks/'
    | '/_authenticated/copilot/'
    | '/_authenticated/costs/'
    | '/_authenticated/customers/'
    | '/_authenticated/financial-indicators/'
    | '/_authenticated/financials/'
    | '/_authenticated/fixed-assets/'
    | '/_authenticated/imports/'
    | '/_authenticated/insights/'
    | '/_authenticated/intelligence/'
    | '/_authenticated/invoices/'
    | '/_authenticated/projects/'
    | '/_authenticated/reports/'
    | '/_authenticated/suppliers/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tax-tools/'
    | '/_authenticated/treasury/'
    | '/_authenticated/trial-balance/'
    | '/_authenticated/vendors/'
    | '/_authenticated/vendors/statement/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/': {
      id: '/_authenticated/vendors/'
      path: '/vendors'
      fullPath: '/vendors/'
      preLoaderRoute: typeof AuthenticatedVendorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/trial-balance/': {
      id: '/_authenticated/trial-balance/'
      path: '/trial-balance'
      fullPath: '/trial-balance/'
      preLoaderRoute: typeof AuthenticatedTrialBalanceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/treasury/': {
      id: '/_authenticated/treasury/'
      path: '/treasury'
      fullPath: '/treasury/'
      preLoaderRoute: typeof AuthenticatedTreasuryIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tax-tools/': {
      id: '/_authenticated/tax-tools/'
      path: '/tax-tools'
      fullPath: '/tax-tools/'
      preLoaderRoute: typeof AuthenticatedTaxToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/suppliers/': {
      id: '/_authenticated/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof AuthenticatedSuppliersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/': {
      id: '/_authenticated/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AuthenticatedProjectsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/invoices/': {
      id: '/_authenticated/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof AuthenticatedInvoicesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence/': {
      id: '/_authenticated/intelligence/'
      path: '/intelligence'
      fullPath: '/intelligence/'
      preLoaderRoute: typeof AuthenticatedIntelligenceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/insights/': {
      id: '/_authenticated/insights/'
      path: '/insights'
      fullPath: '/insights/'
      preLoaderRoute: typeof AuthenticatedInsightsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imports/': {
      id: '/_authenticated/imports/'
      path: '/imports'
      fullPath: '/imports/'
      preLoaderRoute: typeof AuthenticatedImportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fixed-assets/': {
      id: '/_authenticated/fixed-assets/'
      path: '/fixed-assets'
      fullPath: '/fixed-assets/'
      preLoaderRoute: typeof AuthenticatedFixedAssetsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/': {
      id: '/_authenticated/financials/'
      path: '/financials'
      fullPath: '/financials/'
      preLoaderRoute: typeof AuthenticatedFinancialsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financial-indicators/': {
      id: '/_authenticated/financial-indicators/'
      path: '/financial-indicators'
      fullPath: '/financial-indicators/'
      preLoaderRoute: typeof AuthenticatedFinancialIndicatorsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/costs/': {
      id: '/_authenticated/costs/'
      path: '/costs'
      fullPath: '/costs/'
      preLoaderRoute: typeof AuthenticatedCostsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/copilot/': {
      id: '/_authenticated/copilot/'
      path: '/copilot'
      fullPath: '/copilot/'
      preLoaderRoute: typeof AuthenticatedCopilotIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/banks/': {
      id: '/_authenticated/banks/'
      path: '/banks'
      fullPath: '/banks/'
      preLoaderRoute: typeof AuthenticatedBanksIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/top': {
      id: '/_authenticated/vendors/top'
      path: '/vendors/top'
      fullPath: '/vendors/top'
      preLoaderRoute: typeof AuthenticatedVendorsTopRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/aging': {
      id: '/_authenticated/vendors/aging'
      path: '/vendors/aging'
      fullPath: '/vendors/aging'
      preLoaderRoute: typeof AuthenticatedVendorsAgingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/receivables/aging': {
      id: '/_authenticated/receivables/aging'
      path: '/receivables/aging'
      fullPath: '/receivables/aging'
      preLoaderRoute: typeof AuthenticatedReceivablesAgingRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/projects/progress': {
      id: '/_authenticated/projects/progress'
      path: '/projects/progress'
      fullPath: '/projects/progress'
      preLoaderRoute: typeof AuthenticatedProjectsProgressRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence/vendors': {
      id: '/_authenticated/intelligence/vendors'
      path: '/intelligence/vendors'
      fullPath: '/intelligence/vendors'
      preLoaderRoute: typeof AuthenticatedIntelligenceVendorsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/intelligence/customers': {
      id: '/_authenticated/intelligence/customers'
      path: '/intelligence/customers'
      fullPath: '/intelligence/customers'
      preLoaderRoute: typeof AuthenticatedIntelligenceCustomersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/imports/upload': {
      id: '/_authenticated/imports/upload'
      path: '/imports/upload'
      fullPath: '/imports/upload'
      preLoaderRoute: typeof AuthenticatedImportsUploadRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/kpis': {
      id: '/_authenticated/financials/kpis'
      path: '/financials/kpis'
      fullPath: '/financials/kpis'
      preLoaderRoute: typeof AuthenticatedFinancialsKpisRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/income-statement': {
      id: '/_authenticated/financials/income-statement'
      path: '/financials/income-statement'
      fullPath: '/financials/income-statement'
      preLoaderRoute: typeof AuthenticatedFinancialsIncomeStatementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/equity': {
      id: '/_authenticated/financials/equity'
      path: '/financials/equity'
      fullPath: '/financials/equity'
      preLoaderRoute: typeof AuthenticatedFinancialsEquityRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/cash-flow': {
      id: '/_authenticated/financials/cash-flow'
      path: '/financials/cash-flow'
      fullPath: '/financials/cash-flow'
      preLoaderRoute: typeof AuthenticatedFinancialsCashFlowRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/financials/balance-sheet': {
      id: '/_authenticated/financials/balance-sheet'
      path: '/financials/balance-sheet'
      fullPath: '/financials/balance-sheet'
      preLoaderRoute: typeof AuthenticatedFinancialsBalanceSheetRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/import': {
      id: '/_authenticated/customers/import'
      path: '/customers/import'
      fullPath: '/customers/import'
      preLoaderRoute: typeof AuthenticatedCustomersImportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$id': {
      id: '/_authenticated/customers/$id'
      path: '/customers/$id'
      fullPath: '/customers/$id'
      preLoaderRoute: typeof AuthenticatedCustomersIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cash-flow/matrix': {
      id: '/_authenticated/cash-flow/matrix'
      path: '/cash-flow/matrix'
      fullPath: '/cash-flow/matrix'
      preLoaderRoute: typeof AuthenticatedCashFlowMatrixRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/vendors/statement/$id': {
      id: '/_authenticated/vendors/statement/$id'
      path: '/vendors/statement/$id'
      fullPath: '/vendors/statement/$id'
      preLoaderRoute: typeof AuthenticatedVendorsStatementIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedCashFlowMatrixRoute: typeof AuthenticatedCashFlowMatrixRoute
  AuthenticatedCustomersIdRoute: typeof AuthenticatedCustomersIdRoute
  AuthenticatedCustomersImportRoute: typeof AuthenticatedCustomersImportRoute
  AuthenticatedFinancialsBalanceSheetRoute: typeof AuthenticatedFinancialsBalanceSheetRoute
  AuthenticatedFinancialsCashFlowRoute: typeof AuthenticatedFinancialsCashFlowRoute
  AuthenticatedFinancialsEquityRoute: typeof AuthenticatedFinancialsEquityRoute
  AuthenticatedFinancialsIncomeStatementRoute: typeof AuthenticatedFinancialsIncomeStatementRoute
  AuthenticatedFinancialsKpisRoute: typeof AuthenticatedFinancialsKpisRoute
  AuthenticatedImportsUploadRoute: typeof AuthenticatedImportsUploadRoute
  AuthenticatedIntelligenceCustomersRoute: typeof AuthenticatedIntelligenceCustomersRoute
  AuthenticatedIntelligenceVendorsRoute: typeof AuthenticatedIntelligenceVendorsRoute
  AuthenticatedProjectsProgressRoute: typeof AuthenticatedProjectsProgressRoute
  AuthenticatedReceivablesAgingRoute: typeof AuthenticatedReceivablesAgingRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
  AuthenticatedVendorsAgingRoute: typeof AuthenticatedVendorsAgingRoute
  AuthenticatedVendorsTopRoute: typeof AuthenticatedVendorsTopRoute
  AuthenticatedBanksIndexRoute: typeof AuthenticatedBanksIndexRoute
  AuthenticatedCopilotIndexRoute: typeof AuthenticatedCopilotIndexRoute
  AuthenticatedCostsIndexRoute: typeof AuthenticatedCostsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedFinancialIndicatorsIndexRoute: typeof AuthenticatedFinancialIndicatorsIndexRoute
  AuthenticatedFinancialsIndexRoute: typeof AuthenticatedFinancialsIndexRoute
  AuthenticatedFixedAssetsIndexRoute: typeof AuthenticatedFixedAssetsIndexRoute
  AuthenticatedImportsIndexRoute: typeof AuthenticatedImportsIndexRoute
  AuthenticatedInsightsIndexRoute: typeof AuthenticatedInsightsIndexRoute
  AuthenticatedIntelligenceIndexRoute: typeof AuthenticatedIntelligenceIndexRoute
  AuthenticatedInvoicesIndexRoute: typeof AuthenticatedInvoicesIndexRoute
  AuthenticatedProjectsIndexRoute: typeof AuthenticatedProjectsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSuppliersIndexRoute: typeof AuthenticatedSuppliersIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTaxToolsIndexRoute: typeof AuthenticatedTaxToolsIndexRoute
  AuthenticatedTreasuryIndexRoute: typeof AuthenticatedTreasuryIndexRoute
  AuthenticatedTrialBalanceIndexRoute: typeof AuthenticatedTrialBalanceIndexRoute
  AuthenticatedVendorsIndexRoute: typeof AuthenticatedVendorsIndexRoute
  AuthenticatedVendorsStatementIdRoute: typeof AuthenticatedVendorsStatementIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedCashFlowMatrixRoute: AuthenticatedCashFlowMatrixRoute,
  AuthenticatedCustomersIdRoute: AuthenticatedCustomersIdRoute,
  AuthenticatedCustomersImportRoute: AuthenticatedCustomersImportRoute,
  AuthenticatedFinancialsBalanceSheetRoute:
    AuthenticatedFinancialsBalanceSheetRoute,
  AuthenticatedFinancialsCashFlowRoute: AuthenticatedFinancialsCashFlowRoute,
  AuthenticatedFinancialsEquityRoute: AuthenticatedFinancialsEquityRoute,
  AuthenticatedFinancialsIncomeStatementRoute:
    AuthenticatedFinancialsIncomeStatementRoute,
  AuthenticatedFinancialsKpisRoute: AuthenticatedFinancialsKpisRoute,
  AuthenticatedImportsUploadRoute: AuthenticatedImportsUploadRoute,
  AuthenticatedIntelligenceCustomersRoute:
    AuthenticatedIntelligenceCustomersRoute,
  AuthenticatedIntelligenceVendorsRoute: AuthenticatedIntelligenceVendorsRoute,
  AuthenticatedProjectsProgressRoute: AuthenticatedProjectsProgressRoute,
  AuthenticatedReceivablesAgingRoute: AuthenticatedReceivablesAgingRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
  AuthenticatedVendorsAgingRoute: AuthenticatedVendorsAgingRoute,
  AuthenticatedVendorsTopRoute: AuthenticatedVendorsTopRoute,
  AuthenticatedBanksIndexRoute: AuthenticatedBanksIndexRoute,
  AuthenticatedCopilotIndexRoute: AuthenticatedCopilotIndexRoute,
  AuthenticatedCostsIndexRoute: AuthenticatedCostsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedFinancialIndicatorsIndexRoute:
    AuthenticatedFinancialIndicatorsIndexRoute,
  AuthenticatedFinancialsIndexRoute: AuthenticatedFinancialsIndexRoute,
  AuthenticatedFixedAssetsIndexRoute: AuthenticatedFixedAssetsIndexRoute,
  AuthenticatedImportsIndexRoute: AuthenticatedImportsIndexRoute,
  AuthenticatedInsightsIndexRoute: AuthenticatedInsightsIndexRoute,
  AuthenticatedIntelligenceIndexRoute: AuthenticatedIntelligenceIndexRoute,
  AuthenticatedInvoicesIndexRoute: AuthenticatedInvoicesIndexRoute,
  AuthenticatedProjectsIndexRoute: AuthenticatedProjectsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSuppliersIndexRoute: AuthenticatedSuppliersIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTaxToolsIndexRoute: AuthenticatedTaxToolsIndexRoute,
  AuthenticatedTreasuryIndexRoute: AuthenticatedTreasuryIndexRoute,
  AuthenticatedTrialBalanceIndexRoute: AuthenticatedTrialBalanceIndexRoute,
  AuthenticatedVendorsIndexRoute: AuthenticatedVendorsIndexRoute,
  AuthenticatedVendorsStatementIdRoute: AuthenticatedVendorsStatementIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
